services:
    withings:
      image: thunini/withings:1.0.1
      restart: on-failure
      depends_on:
        - mongo-db
      links:
        - mongo-db
    mongo-db:
      image: mongo:latest
      ports:
        - "3001:27017"
      environment:
        - MONGO_INITDB_ROOT_USERNAME=pymongo
        - MONGO_INITDB_ROOT_PASSWORD=pymongo
      volumes:
        - ./mongodb-data:/data/db
